-- ##############################
-----SEAFLOOR MK1

local seafloor_pump = data.raw["offshore-pump"]["angels-seafloor-pump"]
seafloor_pump.flags = seafloor_pump.flags or {}
table.insert(seafloor_pump.flags, "hide-alt-info")
-- seafloor_pump.fluid_box.pipe_connections = {
-- 	{
-- 		direction = defines.direction.south,
-- 		flow_direction = "output",
-- 		position = {
-- 			0,
-- 			0.2,
-- 		},
-- 	},
-- }
-- seafloor_pump.selectable_in_game = false

-- local seafloor_pump_output = table.deepcopy(offshore_pump_output_template)
-- seafloor_pump_output.animations = {
-- 	north = {
-- 		filename = "__angelsrefininggraphics__/graphics/entity/seafloor-pump/seafloor-pump.png",
-- 		width = 160,
-- 		height = 160,
-- 		line_length = 1,
-- 		frame_count = 1,
-- 		animation_speed = 0.5,
-- 		shift = { 0, -1 },
-- 	},
-- 	east = {
-- 		filename = "__angelsrefininggraphics__/graphics/entity/seafloor-pump/seafloor-pump.png",
-- 		width = 160,
-- 		height = 160,
-- 		x = 160,
-- 		line_length = 1,
-- 		frame_count = 1,
-- 		animation_speed = 0.5,
-- 		shift = { 1, 0 },
-- 	},
--
-- 	south = {
-- 		filename = "__angelsrefininggraphics__/graphics/entity/seafloor-pump/seafloor-pump.png",
-- 		width = 160,
-- 		height = 160,
-- 		x = 320,
-- 		line_length = 1,
-- 		frame_count = 1,
-- 		animation_speed = 0.5,
-- 		shift = { 0, 1 },
-- 	},
-- 	west = {
-- 		filename = "__angelsrefininggraphics__/graphics/entity/seafloor-pump/seafloor-pump.png",
-- 		width = 160,
-- 		height = 160,
-- 		x = 480,
-- 		line_length = 1,
-- 		frame_count = 1,
-- 		animation_speed = 0.5,
-- 		shift = { -1, 0 },
-- 	},
-- }
-- seafloor_pump_output.name = "angels-seafloor-pump-output"
-- seafloor_pump_output.icon = "__angelsrefininggraphics__/graphics/icons/seafloor-pump-ico.png"
-- seafloor_pump_output.icon_size = 32
-- seafloor_pump_output.localised_name = { "entity-name.angels-seafloor-pump" }
-- seafloor_pump_output.minable = seafloor_pump.minable
-- seafloor_pump_output.placeable_by = { item = "angels-seafloor-pump", count = 1 }
-- seafloor_pump_output.pumping_speed = seafloor_pump.pumping_speed
-- seafloor_pump_output.selectable_in_game = true
-- -- seafloor_pump_output.create_ghost_on_death = false --test
-- seafloor_pump_output.selection_box = seafloor_pump.selection_box
-- seafloor_pump_output.energy_source =
-- 	{ type = "electric", usage_priority = "secondary-input", emissions_per_minute = { pollution = 10 } }
-- seafloor_pump_output.energy_usage = "500kW"
-- data:extend({ seafloor_pump_output })
